language: go

env:
  global:
    - GO111MODULE=ON

matrix:
  include:
    - os: linux
      dist: trusty
      go: 1.11.x
      script:
        - make check
        - make deps
        - make test
    - os: linux
      dist: trusty
      go: 1.12.x
      script:
        - make check
        - make deps
        - make test
